#!/bin/bash

echo "🚀 AasraSewa Deployment Setup"
echo "=============================="

echo ""
echo "📋 Prerequisites Checklist:"
echo "1. GitHub repository with code pushed ✅"
echo "2. MongoDB Atlas account (free) - https://mongodb.com"
echo "3. Cloudinary account (free) - https://cloudinary.com"
echo "4. Stripe account (free) - https://stripe.com"
echo "5. OpenAI API key - https://platform.openai.com"
echo "6. Google Gemini API key - https://makersuite.google.com/app/apikey"

echo ""
echo "🔧 Environment Variables Needed:"
echo ""
echo "Backend (.env):"
echo "FRONTEND_URL=https://aasrasewa-frontend.onrender.com"
echo "PORT=3000"
echo "MONGO_URI=your_mongodb_connection_string"
echo "JWT_SECRET=your_very_long_random_secret_key"
echo "EXPIRE_IN=1d"
echo "NODE_ENV=production"
echo "STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key"
echo "CLOUDINARY_CLOUD_NAME=your_cloudinary_cloud_name"
echo "CLOUDINARY_API_KEY=your_cloudinary_api_key"
echo "CLOUDINARY_API_SECRET=your_cloudinary_api_secret"
echo ""
echo "ML Service (.env):"
echo "OPENAI_API_KEY=sk-proj-your_openai_api_key"
echo "GEMINI_API_KEY=AIzaSy-your_gemini_api_key"
echo "VITE_CLOUDINARY_URL=cloudinary://your_api_key:your_api_secret@your_cloud_name"
echo "VITE_CLOUDINARY_CLOUD_NAME=your_cloudinary_cloud_name"
echo "MONGO_URI=your_mongodb_connection_string"
echo ""
echo "Frontend (.env):"
echo "VITE_API_URL=https://aasrasewa-backend.onrender.com"
echo "VITE_CLOUDINARY_URL=cloudinary://your_api_key:your_api_secret@your_cloud_name"
echo "VITE_CLOUDINARY_CLOUD_NAME=your_cloudinary_cloud_name"
echo "VITE_STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_publishable_key"
echo ""
echo "Admin (.env):"
echo "VITE_API_BASE_URL=https://aasrasewa-backend.onrender.com/api"

echo ""
echo "🎯 Next Steps:"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Follow the DEPLOYMENT_GUIDE.md"
echo "4. Deploy services in this order:"
echo "   - Backend API"
echo "   - ML Service"
echo "   - Frontend"
echo "   - Admin Panel"

echo ""
echo "📚 Full guide available in: DEPLOYMENT_GUIDE.md"
echo "💰 Total cost: $0/month (completely free!)" 